services:
  app:
    image: aidly/aid-ly
    env_file: '.env'
    depends_on:
      - migrate
      - pgbouncer
    ports:
      - '3000:3000'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    restart: 'unless-stopped'
    networks:
      - backend

  migrate:
    image: aidly/aid-ly
    command: pnpm prisma migrate deploy
    env_file: '.env'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    restart: 'no'
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aidly
    networks:
      - backend
    expose:
      - '5432'

  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_USERS=${POSTGRES_USER}
      - AUTH_TYPE=md5
    expose:
      - '5432'
    networks:
      - backend

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --http-api-update --label-enable
    env_file: '.env'
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    ports:
      - '3001:8080'
    restart: unless-stopped
    depends_on:
      - app

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
