services:
  app:
    image: aid-ly/aid-ly
    env_file: '.env'
    depends_on:
      - migrate
    ports:
      - '3000:3000'
    restart: 'unless-stopped'

  migrate:
    image: aid-ly/aid-ly
    command: pnpm prisma migrate deploy
    env_file: '.env'
    restart: 'no'
